"""initial schema

Revision ID: a3f003714b1b
Revises:
Create Date: 2026-08-02 15:46:02.525608
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a3f003714b1b"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contribution_id", sa.String(length=64), nullable=True),
        sa.Column("command_json", sa.JSON(), nullable=False),
        sa.Column("working_directory", sa.String(length=1024), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("stdout_excerpt", sa.Text(), nullable=False),
        sa.Column("stderr_excerpt", sa.Text(), nullable=False),
        sa.Column("timed_out", sa.Boolean(), nullable=False),
        sa.Column("risk_classification", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_runs_contribution_id"), "command_runs", ["contribution_id"], unique=False
    )
    op.create_table(
        "contributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contribution_id", sa.String(length=64), nullable=False),
        sa.Column("repository_full_name", sa.String(length=255), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("base_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("branch_name", sa.String(length=255), nullable=True),
        sa.Column("pull_request_url", sa.String(length=512), nullable=True),
        sa.Column("resume_bullet", sa.Text(), nullable=True),
        sa.Column("extra_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contributions_contribution_id"), "contributions", ["contribution_id"], unique=True
    )
    op.create_index(
        op.f("ix_contributions_repository_full_name"),
        "contributions",
        ["repository_full_name"],
        unique=False,
    )
    op.create_index(op.f("ix_contributions_state"), "contributions", ["state"], unique=False)
    op.create_table(
        "http_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_key", sa.String(length=1024), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("last_modified", sa.String(length=255), nullable=True),
        sa.Column("body_json", sa.JSON(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_http_cache_request_key"), "http_cache", ["request_key"], unique=True)
    op.create_table(
        "issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_full_name", sa.String(length=255), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("score_json", sa.JSON(), nullable=True),
        sa.Column("score_total", sa.Integer(), nullable=True),
        sa.Column("rejected", sa.Boolean(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_issues_repo_number", "issues", ["repository_full_name", "number"], unique=True
    )
    op.create_index(
        op.f("ix_issues_repository_full_name"), "issues", ["repository_full_name"], unique=False
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_category", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("response_hash", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cache_status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_calls_prompt_hash"), "llm_calls", ["prompt_hash"], unique=False)
    op.create_index(
        op.f("ix_llm_calls_task_category"), "llm_calls", ["task_category"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("score_json", sa.JSON(), nullable=True),
        sa.Column("score_total", sa.Integer(), nullable=True),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_full_name"), "projects", ["full_name"], unique=True)
    op.create_index(op.f("ix_projects_score_total"), "projects", ["score_total"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("approval_id", sa.String(length=64), nullable=False),
        sa.Column("contribution_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contribution_id"],
            ["contributions.contribution_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_approval_id"), "approvals", ["approval_id"], unique=True)
    op.create_index(
        op.f("ix_approvals_contribution_id"), "approvals", ["contribution_id"], unique=False
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contribution_id", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=64), nullable=False),
        sa.Column("to_state", sa.String(length=64), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contribution_id"],
            ["contributions.contribution_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transitions_contribution",
        "workflow_transitions",
        ["contribution_id", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transitions_contribution_id"),
        "workflow_transitions",
        ["contribution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_transitions_contribution_id"), table_name="workflow_transitions"
    )
    op.drop_index("ix_transitions_contribution", table_name="workflow_transitions")
    op.drop_table("workflow_transitions")
    op.drop_index(op.f("ix_approvals_contribution_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_approval_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_projects_score_total"), table_name="projects")
    op.drop_index(op.f("ix_projects_full_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_llm_calls_task_category"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_prompt_hash"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_issues_repository_full_name"), table_name="issues")
    op.drop_index("ix_issues_repo_number", table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_http_cache_request_key"), table_name="http_cache")
    op.drop_table("http_cache")
    op.drop_index(op.f("ix_contributions_state"), table_name="contributions")
    op.drop_index(op.f("ix_contributions_repository_full_name"), table_name="contributions")
    op.drop_index(op.f("ix_contributions_contribution_id"), table_name="contributions")
    op.drop_table("contributions")
    op.drop_index(op.f("ix_command_runs_contribution_id"), table_name="command_runs")
    op.drop_table("command_runs")
    # ### end Alembic commands ###
